### ISSUE TITLE
[Suggestion] New Config Options (mostly for dodging)

### ISSUE THREAD

**Issue by ZilverLazarus** [alRex-U/ParCool#113]
Playing around with this mod, it's exactly what I need to recreate the movement system I had for my modpack in 1.16.5. However, there are a few options missing from the config that I think should be included.

1). The ability to dodge mid-air. (Disabled by default in the config)
2). Let us adjust the horizontal (and maybe vertical) velocity of dodges.
3). Make cooldowns between actions adjustable, including dodging. 

Hopefully these are considered for inclusion into this amazing mod. Keep up the good work.

**Comment by alRex-U** [comment]
Thank-you for suggesting.

As for the first you said, sorry, but maybe I won't do that. Probably it would looks unnatural because players could jump in air(just like double-jump, I have decided not to add actions which be physically difficult even by real parkour player)

About the second and third, it sounds not bad. However I need to modify the values carefully because they are mainly for that players cannot use dodge for movement.
In particular, a config of cooldown may be going to be an item of server config in order not to make players unfair in same world.
