### ISSUE TITLE
Feathers doesn't limit parcool

### ISSUE THREAD

**Issue by Orgamorsh** [alRex-U/ParCool#169]
Feathers doesn't limit parcool

**Running Environment**
+ Minecraft Version: 1.18.2
+ ParCool Version:3.0.1.0-R
+ Feathers Version:1.0.4

**Detail**
When all feathers are depleted, you can continue using parcool without stamina cost.

**Comment by alRex-U** [comment]
Oh, I want to confirm but isn't it that just you use parcool action just when feathers recover?

**Comment by Orgamorsh** [comment]
Well, my config has dodge use 3 feathers. I can still dodge when I have less than three feathers.

**Comment by alRex-U** [comment]
It is normal behavior, players can use parcool actions if their stamina values are remaining at least 1 point, even if it is not over the stamina consumption of the action.

This is the same when you use Feathers.
When you cannot use ParCool is only when you run out your Feathers completely.

I think this is caused by system difference between ParCool's stamina and Feathers.(Feathers doesn't have "exhausted" state)

Indeed, it might be better if I could make Feathers stamina behave as you said, but this should be quite troublesome.
