### ISSUE TITLE
[Suggestion] Add Hang Down compat with many mods' chains and ropes 

### ISSUE THREAD

**Issue by Catomax262** [alRex-U/ParCool#184]
**Summary**
The fact that some horizontal chain variants or rope from other mods aren't hang-down-able or climbable bugs me out.

I'd like a config option so we can define which blocks you can climb/hang down from.

But i kinda see the ropes as a huge potential for hang-downs (as they're already climbable), so making them compatible by default would be a great idea.
(Rope from Supplementaries and Rope from XercaMod have a horizontal rope walking feature that would pair very well)

**Comment by alRex-U** [comment]
Also I wanted to support blocks added by other mods but I could not do because of a technical issue.

At first I try to enable Hang down action to any blocks having *axis*. This worked correctly, except the fact that players can hang down from not thin blocks, such as quartz pillar block.

Anyway I will try it in next update.

**Comment by alRex-U** [comment]
For moment, I made the expression of hang-able blocks more abstract.
