### ISSUE TITLE
[1.12.2] Some render problem

### ISSUE THREAD

**Issue by HuangAdam** [alRex-U/ParCool#22]
**Summary**
Some render problem

**Running Environment**
+ Minecraft Version: 1.12.2
+ ParCool Version: ParCool-1.12.2-1.0.0.0-α
+ Forge Version (optional): 14.23.5.2855

**Detail**
There is only ParCool mod.
Some actions are not correct to render, such crawl, roll, sliding and grab cliff.

**Additional Data**
Normal:
![2021-07-12_07 29 24](https://user-images.githubusercontent.com/46439030/125213088-d8f01b80-e2e3-11eb-9315-dbbcccb0bf8f.png)

Crawl:
![2021-07-12_07 29 27](https://user-images.githubusercontent.com/46439030/125213108-e9a09180-e2e3-11eb-8d94-ed060953f307.png)

Grab cliff:
![2021-07-12_07 37 56](https://user-images.githubusercontent.com/46439030/125213234-2076a780-e2e4-11eb-8079-a04ff40beb19.png)

Sliding:
![2021-07-12_07 40 42](https://user-images.githubusercontent.com/46439030/125213319-85ca9880-e2e4-11eb-895e-aaaa31e99734.png)

**Comment by alRex-U** [comment]
Thank you for reporting!

ParCool in 1.16.1 has custom renderer, but actually implementation in 1.12 has no them(exactly speaking those are only disabled). This is because i thought implementing in 1.12 takes much time.

I am going to fix it but now i am a little busy and have no idea about a bug  which i want to fix first(#18) so i cannot do it soon,sorry.

**Comment by HuangAdam** [comment]
Thanks for your quick answer.
It is a great mod. I will keep focus on it.
Waiting for your update.
