### ISSUE TITLE
[Suggestion] Config that allow us to remove the double-tap key feature for movements.

### ISSUE THREAD

**Issue by 2sumango** [alRex-U/ParCool#36]
**Summary**

Could we get a config option to disable parcool movements from double tapping keys (W, A, S D)  Sometimes, I find myself barely hitting the keys once doing a movement involuntarily, and I don't want to have to keep disabling and enabling the mod because it kind of takes away the immersion. 

I'd also like to add one more small suggestion.  A config option to hide the parcool hud in the bottom right that shows the stamina.
Thanks in advance!

**Running Environment**
+ Minecraft 1.12.2
+ ParCool-1.12.2-1.0.0.0-α
+ Forge - 14.23.5.2854

**Comment by alRex-U** [comment]
Thank you for suggesting!

I've been received this suggestion once, but i could not do this because i have no alternative idea. Also I think double tapping  is not necessarily user-friendly.

As for hiding hud, this has already been implenented in latest version of 1.16 so it will be also done.

Anyway now i have other things to do. Thus i cannot do this soon, sorry.(this project always accept your contribution.)
